name = input('请输入姓名：')
company = input('请输入公司：')
title = input('请输入职位')
tel = input('请输入号码')
email = input('请输入邮箱')

print('*'*50)
print(company)
print()
print("%s(%s)"%(name,title))
print()
print('电话:%s'%tel)
print('邮箱:%s'%email)
print('*'*50)